# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnpDFODU3YVjQlm9p5GX_pbaodyYg52N
"""

import gradio as gr
import torch
import torchvision.models as models
import torchvision.transforms as transforms

import pandas as pd
import numpy as np
import joblib

from PIL import Image

# -----------------------------------
# Load deployment artifacts
# -----------------------------------

bundle = joblib.load("melanoma_pipeline.pkl")

model = bundle["model"]
scaler = bundle["scaler"]
selector = bundle["selector"]
encoder = bundle["encoder"]
threshold = bundle["threshold"]

encoded_feature_order = joblib.load(
    "encoded_feature_order.pkl"
)

# -----------------------------------
# Device setup
# -----------------------------------

device = torch.device("cpu")

# -----------------------------------
# ResNet18 feature extractor
# -----------------------------------

resnet = models.resnet18(weights="DEFAULT")

# Remove classification head
resnet = torch.nn.Sequential(
    *list(resnet.children())[:-1]
)

resnet.eval()
resnet.to(device)

# -----------------------------------
# Image preprocessing
# -----------------------------------

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# -----------------------------------
# Prediction function
# -----------------------------------

def predict(image, age, sex, site):

    # -----------------------------
    # Validate image
    # -----------------------------

    if image is None:
        return "Please upload an image."

    # -----------------------------
    # IMAGE FEATURES
    # -----------------------------

    img = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():

        img_features = resnet(img)

        img_features = img_features.view(
            img_features.size(0), -1
        )

        img_features = img_features.cpu().numpy()

    # -----------------------------
    # METADATA
    # -----------------------------

    metadata = pd.DataFrame([{
        "sex": sex,
        "age_approx": age,
        "anatom_site_general_challenge": site
    }])

    encoded_meta = encoder.transform(metadata)

    encoded_meta = pd.DataFrame(
        encoded_meta,
        columns=encoded_feature_order
    )

    # -----------------------------
    # COMBINE FEATURES
    # -----------------------------

    X = np.hstack([
        img_features,
        encoded_meta.values
    ])

    # -----------------------------
    # PREPROCESSING
    # -----------------------------

    X = selector.transform(X)

    X = scaler.transform(X)

    # -----------------------------
    # PREDICT
    # -----------------------------

    probability = model.predict_proba(X)[0, 1]

    prediction = (
        "Higher Melanoma Risk"
        if probability > threshold
        else "Lower Melanoma Risk"
    )

    probability = round(float(probability), 4)

    # -----------------------------
    # RETURN OUTPUT
    # -----------------------------

    return (
        f"Prediction: {prediction}\n\n"
        f"Melanoma Probability: {probability}"
    )

# -----------------------------------
# Gradio Interface
# -----------------------------------

demo = gr.Interface(
    fn=predict,

    inputs=[
        gr.Image(
            type="pil",
            label="Upload Skin Lesion Image"
        ),

        gr.Slider(
            minimum=0,
            maximum=100,
            value=45,
            step=1,
            label="Age"
        ),

        gr.Dropdown(
            ["male", "female", "unknown"],
            value="unknown",
            label="Sex"
        ),

        gr.Dropdown(
            [
                "torso",
                "lower extremity",
                "upper extremity",
                "head/neck",
                "unknown"
            ],
            value="unknown",
            label="Anatomical Site"
        )
    ],

    outputs=gr.Textbox(
        label="Prediction Result"
    ),

    title="Melanoma Risk Assessment",

    description="""
AI-powered melanoma risk assessment using:
• ResNet18 image embeddings
• Clinical metadata
• Logistic Regression

Educational research prototype only.
Not intended for clinical diagnosis.
"""
)

# -----------------------------------
# Launch app
# -----------------------------------

demo.launch(
    share=True,
    show_api=False
)