# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnpDFODU3YVjQlm9p5GX_pbaodyYg52N
"""

import gradio as gr
import pandas as pd
import numpy as np
import joblib
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image

# =========================
# LOAD TABULAR MODEL
# =========================

pipeline = joblib.load("melanoma_pipeline.pkl")
feature_order = joblib.load("encoded_feature_order.pkl")

# =========================
# CNN MODEL
# =========================

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 56 * 56, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.fc(x)
        return x

cnn_model = SimpleCNN()

# OPTIONAL MODEL LOAD
try:
    cnn_model.load_state_dict(
        torch.load("melanoma_model.pth", map_location=torch.device("cpu"))
    )
    print("CNN model loaded successfully.")
except:
    print("melanoma_model.pth not found. Using untrained CNN.")

cnn_model.eval()

# =========================
# IMAGE TRANSFORM
# =========================

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

# =========================
# TABULAR PREDICTION
# =========================

def predict_tabular(
    age,
    sex,
    localization,
    diameter,
    elevation,
    color,
):

    input_dict = {
        "age": [age],
        "sex": [sex],
        "localization": [localization],
        "diameter": [diameter],
        "elevation": [elevation],
        "color": [color],
    }

    df = pd.DataFrame(input_dict)

    pred_prob = pipeline.predict_proba(df)[0][1]

    result = f"Melanoma Risk Probability: {pred_prob:.2%}"

    return result

# =========================
# IMAGE PREDICTION
# =========================

def predict_image(image):

    if image is None:
        return "Please upload an image."

    image = transform(image).unsqueeze(0)

    with torch.no_grad():
        prediction = cnn_model(image).item()

    result = f"CNN Melanoma Probability: {prediction:.2%}"

    return result

# =========================
# GRADIO UI
# =========================

with gr.Blocks() as demo:

    gr.Markdown("# Melanoma Detection App")

    with gr.Tab("Tabular Prediction"):

        age = gr.Number(label="Age")

        sex = gr.Dropdown(
            choices=["male", "female"],
            label="Sex"
        )

        localization = gr.Textbox(label="Localization")

        diameter = gr.Number(label="Diameter")

        elevation = gr.Dropdown(
            choices=["flat", "raised"],
            label="Elevation"
        )

        color = gr.Textbox(label="Color")

        tabular_btn = gr.Button("Predict")

        tabular_output = gr.Textbox(label="Prediction")

        tabular_btn.click(
            fn=predict_tabular,
            inputs=[
                age,
                sex,
                localization,
                diameter,
                elevation,
                color
            ],
            outputs=tabular_output
        )

    with gr.Tab("Image Prediction"):

        image_input = gr.Image(
            type="pil",
            label="Upload Skin Lesion Image"
        )

        image_btn = gr.Button("Predict")

        image_output = gr.Textbox(label="Prediction")

        image_btn.click(
            fn=predict_image,
            inputs=image_input,
            outputs=image_output
        )

# =========================
# LAUNCH
# =========================

demo.launch(share=True)